language: c
sudo: false
matrix:
  include:
  - env: CABALVER=1.16 GHCVER=7.6.3
    compiler: "gcc -Icache-hack-ghc-7.6.3"
    addons:
      apt:
        packages:
        - cabal-install-1.16
        - ghc-7.6.3
        - happy-1.19.5
        sources:
        - hvr-ghc
  - env: CABALVER=1.18 GHCVER=7.8.4
    compiler: "gcc -Icache-hack-ghc-7.8.4"
    addons:
      apt:
        packages:
        - cabal-install-1.18
        - ghc-7.8.4
        - happy-1.19.5
        sources:
        - hvr-ghc
  - env: CABALVER=1.22 GHCVER=7.10.2
    compiler: "gcc -Icache-hack-ghc-7.10.2"
    addons:
      apt:
        packages:
        - cabal-install-1.22
        - ghc-7.10.2
        - happy-1.19.5
        sources:
        - hvr-ghc
  - env: CABALVER=head GHCVER=head
    compiler: "gcc -Icache-hack-ghc-head"
    addons:
      apt:
        packages:
        - cabal-install-head
        - ghc-head
        - happy-1.19.5
        sources:
        - hvr-ghc
  allow_failures:
  - env: CABALVER=head GHCVER=head
  fast_finish: true
before_install:
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/1.19.5/bin:$PATH
install:
- cabal --version
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo
  '?')]"
- travis_retry cabal update
- sed -i 's/^jobs:.*$/jobs:2/' ${HOME}/.cabal/config
- cabal install --only-dependencies --enable-tests --enable-benchmarks
script:
- if [ -f configure.ac ]; then autoreconf -i; fi
- cabal configure --enable-tests --enable-benchmarks -v2
- cabal build
- cabal test
- cabal sdist
- SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz && (cd dist && cabal install
  --force-reinstalls "$SRC_TGZ")
notifications:
  slack:
    secure: ZZaRDOwwSSTIAudI/L+qZY/1uc+fMzfpLN19BTPOQuSb+6krkpIA+sKkBcCp0r9yZXKpqdCtnrbogeQoJSy/tI5VjAHZoXHJz23IypjsgGZ5utqbMmuaB3BWObUP1dIWBo30iLYJJFUxKKuqpIaLVeQWTP2NDgkdYW0H5ERGhGvF2lWvwNhpW3fQxnmsRlWdV5wlSVdemOeCxF7LeJt7W9RnhcnDmwChpTPNGu24NdrqY2MtU4z43KsbjZGH7M/Rh7keZUd/D8LvcYSHofClaDkQT8FaCZ7LI6ADnbXge7NGtje1ASSL1v8oi7xXMwufiuuXJ8bIQPQBm62W/T2bnP3dnYjoZn4vVguoYfzZAcSaAbjHM06RaTzIn4gZNjXvCuj/w2qEbobiwmY8uDZ5f7Ro9En1gDGvJsvevmoCmBWp7OHJONoBlnpg6Ir8HdJlkImE7kD2jEwOoQTgPoh5CU6izO/lu5ZtqmLuVpFk+XzRwESj7v3ccQd4FQ8rdaQckxKVAWEBJM4aqhBAoQTafI6pt6VjlwB+5UX9wh9JtesBjBxhnpusCGv9GfQfi2WGeFQ9fZcLSztehcal0Nlq3QoQtMx2D+VTfUPbr7VVozkzpWtp/kN3aWhYaZgr3QwO8VaEZK7a4V71XgjSomSeV6rOJz2NkjJhFGezN05WKVs=
cache:
  directories:
  - $HOME/.cabal
  - $HOME/.ghc